### ISSUE TITLE
Hide files for which the filter hasn't found a match

### ISSUE THREAD

**Issue by Janiczek** [jlengrand/vscode-elm-signature#20]
Currently it shows all files:
![results](https://user-images.githubusercontent.com/149425/44312232-3073a380-a3f5-11e8-84af-bee658094a74.png)

**Comment by jlengrand** [comment]
Ha, interesting I was actually pretty happy about that behavior (or lack of). That avoids having files appear / disappear. 

I take not of it :).

**Comment by Janiczek** [comment]
When there's a lot of files, you actually have to scroll a fair amount to get to the actual matches. Maybe there are other ways around the problem? Like eg. sorting it so that files that do have matches show first?

**Comment by jlengrand** [comment]
Hey there, 

I'm surprised you can actually use the extension where there are a lot of files and that it doesn't completely freeze the UI. 

I made a PR yesterday that implements your suggestion actually. I actually like it better that way too.

BTW, I am still investigating what the best way to use this actually is. Was wondering if something more like https://github.com/Krzysztof-Cieslak/vscode-elm/blob/master/images/gotoDefinition.gif would be better. 


Consider this as WIP, suggestions are more than welcome.

**Comment by Janiczek** [comment]
Yeah I've checked out that branch, built it and tried it in VS Code and it seems better to me too :) :+1:

**Comment by jlengrand** [comment]
Thanks for the validation!
